version: "3.7"

services:
  dontownsendcreativeportfolio:
    container_name: dontownsend-creative-portfolio
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      # will bust the cache after `ARG CACHEBUST=1`
      - CACHEBUST=2
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - dontownsendcreativeportfolio
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email donjuancodes@gmail.com --agree-tos --no-eff-email --force-renewal -d dontownsendcreative.com  -d www.dontownsendcreative.com
